server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/user/workspace/git-local-repo
#        native:
#          search-locations: file://Users/user/workspace/git-local-repo
